name: Trigger auto deployment for container-app-kaofgrtt4jv54

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'cypress/fixtures/api/**'
    - '.github/workflows/container-app-kaofgrtt4jv54-AutoDeployTrigger-0861537a-a178-4c38-b239-a80bbec34b61.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPKAOFGRTT4JV54_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPKAOFGRTT4JV54_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPKAOFGRTT4JV54_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/cypress/fixtures/api 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPKAOFGRTT4JV54_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPKAOFGRTT4JV54_REGISTRY_PASSWORD }}
          containerAppName: container-app-kaofgrtt4jv54
          resourceGroup: staticwebappscli9a38
          imageToBuild: default/container-app-kaofgrtt4jv54:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


