name: Trigger auto deployment for container-app-rnifvo6epdmtq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'cypress/fixtures/api/**'
    - '.github/workflows/container-app-rnifvo6epdmtq-AutoDeployTrigger-72adc35c-e71e-427e-a114-815d656ba4d7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPRNIFVO6EPDMTQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPRNIFVO6EPDMTQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPRNIFVO6EPDMTQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/cypress/fixtures/api 
          registryUrl: defaultacrcontainerregistry8dcf.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPRNIFVO6EPDMTQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPRNIFVO6EPDMTQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-rnifvo6epdmtq
          resourceGroup: staticwebappsclib2e5
          imageToBuild: defaultacrcontainerregistry8dcf.azurecr.io/container-app-rnifvo6epdmtq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


